import json
import os
import time
import requests
from dotenv import load_dotenv

# Load the API key securely from your .env file
load_dotenv()
VT_API_KEY = os.getenv("VT_API_KEY")

if not VT_API_KEY:
    raise ValueError("[-] VT_API_KEY not found. Please check your .env file.")

HEADERS = {
    "accept": "application/json",
    "x-apikey": VT_API_KEY
}

def load_extracted_data(filename="extracted_iocs.json"):
    """Loads the JSON data generated by our AI in Phase 3."""
    filepath = os.path.join(os.path.dirname(__file__), "..", "data", "output", filename)
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)

def query_virustotal(ioc, ioc_type):
    """Queries the VirusTotal v3 API for a specific IoC."""
    # Map our internal types to VirusTotal's API endpoints
    endpoints = {
        "ips": f"https://www.virustotal.com/api/v3/ip_addresses/{ioc}",
        "domains": f"https://www.virustotal.com/api/v3/domains/{ioc}",
        "hashes": f"https://www.virustotal.com/api/v3/files/{ioc}"
    }
    
    url = endpoints.get(ioc_type)
    if not url:
        return {"error": "Unsupported IoC type"}

    print(f"  [~] Querying VirusTotal for {ioc_type[:-1]}: {ioc}...")
    response = requests.get(url, headers=HEADERS)
    
    if response.status_code == 200:
        data = response.json()
        # Extract just the malicious/harmless stats to keep our JSON clean
        stats = data.get("data", {}).get("attributes", {}).get("last_analysis_stats", {})
        return {"status": "success", "malicious_score": stats.get("malicious", 0), "total_vendors": sum(stats.values())}
    elif response.status_code == 400:
        return {"status": "invalid", "error": "VirusTotal rejected this as an invalid format (Likely AI Hallucination)."}
    elif response.status_code == 404:
        return {"status": "not_found", "error": "No data found on VirusTotal."}
    elif response.status_code == 429:
        print("  [!] Rate limit hit! Sleeping for 60 seconds...")
        time.sleep(60)
        return query_virustotal(ioc, ioc_type) # Retry
    else:
        return {"status": "error", "error": f"HTTP {response.status_code}"}

if __name__ == "__main__":
    print("[*] Starting Phase 4: Contextual Enrichment Pipeline...")
    articles = load_extracted_data()
    
    for article in articles:
        iocs = article.get("extracted_intelligence", {})
        enrichment_results = {}
        
        # Check IPs, Domains, and Hashes
        for ioc_type in ["ips", "domains", "hashes"]:
            for item in iocs.get(ioc_type, []):
                # Query VT
                vt_result = query_virustotal(item, ioc_type)
                enrichment_results[item] = vt_result
                
                # Sleep to respect the 4 requests/minute limit of the free API
                time.sleep(15) 
                
        # Append the new VT data directly to the article's dictionary
        article["enrichment_data"] = enrichment_results

    # Save the final enriched data
    out_dir = os.path.join(os.path.dirname(__file__), "..", "data", "output")
    out_file = os.path.join(out_dir, "enriched_iocs.json")
    
    with open(out_file, 'w', encoding='utf-8') as f:
        json.dump(articles, f, indent=4)
        
    print(f"\n[+] Phase 4 Complete. Saved enriched IoCs to {out_file}")